# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f8a687ed30831eef52b030e9e25e43a7298b509d111ca38efe95f5316a60513db8395f46cc2eed2a742d4543469c93a76e59a07d888faa450c5eeecbc06c48c

test:
  secret_key_base: d0febc1edd427af30bd848b12de7940e77c8ba60d0bff3bcdaede7cce775a4de2eb3f278e709002aad25da018acf90626f1297e1318b6e16f3927c8e7a4e99a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
